name: "Update VS Code screenshots"
on:
  push:
    branches: "main"
  pull_request:
  workflow_dispatch:

jobs:
  update-screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install VS Code
        run: brew install --cask visual-studio-code

      - name: Start VS Code Server
        run: code serve-web --port 8000 --without-connection-token --accept-server-license-terms

      - name: Install Python and dependencies
        run: uv pip install selenium
        
      - name: Run screenshot scripts
        run: python tools/selenium/run.py
